[2021-05-25 09:24:31,904] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Create_tables 2019-01-13T04:00:00+00:00 [queued]>
[2021-05-25 09:24:31,914] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Create_tables 2019-01-13T04:00:00+00:00 [queued]>
[2021-05-25 09:24:31,914] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-25 09:24:31,914] {taskinstance.py:880} INFO - Starting attempt 1 of 4
[2021-05-25 09:24:31,914] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-25 09:24:31,921] {taskinstance.py:900} INFO - Executing <Task(PostgresOperator): Create_tables> on 2019-01-13T04:00:00+00:00
[2021-05-25 09:24:31,924] {standard_task_runner.py:53} INFO - Started process 6770 to run task
[2021-05-25 09:24:31,977] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: udac_example_dag.Create_tables 2019-01-13T04:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-05-25 09:24:31,994] {taskinstance.py:1145} ERROR - create_tables.sql
Traceback (most recent call last):
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 750, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/dhrebenach/opt/anaconda3/envs/data_pipelines_proj/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2021-05-25 09:24:31,998] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2021-05-25 09:24:41,898] {logging_mixin.py:112} INFO - [2021-05-25 09:24:41,897] {local_task_job.py:103} INFO - Task exited with return code 1
